global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@localhost.com'

route:
  receiver: 'web.hook'

receivers:
  - name: 'web.hook'
    webhook_configs:
      - url: 'http://127.0.0.1:5001/'
        send_resolved: true
