package com.leucine.streem.dto.response;

public enum ErrorCode {
  // Checklist
  PROCESS_NOT_FOUND("E101", "Process not Found"),
  PROCESS_NOT_PUBLISHED("E102", "Process not published"),
  PROCESS_CANNOT_BE_MODFIFIED("E103", "Process cannot be modified"),
  USER_NOT_ALLOWED_TO_MODIFY_PROCESS("E103", "User not allowed to modify process"),
  CANNOT_ASSIGN_COLLABORATOR("E106", "User cannot be assigned as he/she has already assiged or has not been part of review."),
  CANNOT_UNASSIGN_COLLABORATOR("E104", "User cannot be unassigned as he/she has already started or has been part of review."),
  ONLY_PRIMARY_AUTHORS_ALLOWED("E105", "Only prototype owner is allowed to perform the operation."),
  PRIMARY_AUTHOR_CANNOT_BE_APPROVER("E106", "Primary author cannot be approver."),
  //  CANNOT_UNASSIGN_REVIEWER("E106", "User cannot be unassigned as he/she has already started or has been part of review."),
  //  ALREADY_ASSIGNED_FOR_REVIEWING("E106", "Already assigned for reviewing."),
//  CHECKLIST_NOT_IN_REVIEW_STATE("E108", "Checklist not in being reviewed or change request in progress state."),
//  CANNOT_START_AN_ALREADY_STARTED_REVIEW("E109", "Cannot start an already started review"),
//  CANNOT_COMPLETE_AN_REVIEW_THAT_IS_NOT_STARTED("E110", "Cannot complete an review which is not started"),
//  CANNOT_CONTINUE_A_REVIEW_THAT_IS_NOT_DONE("E111", "Cannot continue reviewing that is not completed"),
//  CANNOT_SEND_TO_AUTHOR("E112", "Cannot send to author as you have not completed/done with review"),
  PROCESS_INVALID_STATE_ACTION("E113", "Action performed on the process is invalid on current state"),
  //  CHECKLIST_ALREADY_BEING_REVIEWED("E114", "Checklist is already being reviewed"),
//  CHECKLIST_ALREADY_READY_FOR_RELEASE("E115", "Checklist is already ready for release"),
  PROCESS_ARCHIVED_VALIDATION("E116", "Checklist is archived and cannot be modified"),
  PROCESS_AUTHOR_ALREADY_ASSIGNED("E117", "Author is already assigned to process"),
  PROCESS_AUTHOR_NOT_ASSIGNED("E118", "Author is not assigned to process"),
  CANNOT_UNASSIGN_PRIMARY_AUTHOR_FROM_PROCESS("E119", "Cannot unassign primary author from process"),
  CANNOT_ARCHIVE_PROCESS_WITH_ACTIVE_JOBS("E120", "Process can't be archived as there are active Jobs for it"),
  CANNOT_START_REVISION_FROM_NON_PUBLISHED_PROCESS("E121", "Cannot start a revision from a non-published process"),
  REVISION_ALREADY_BEING_BUILT("E122", "This process is already being Revised. You Cannot revise it again."),
  PROCESS_BY_TASK_NOT_FOUND("E123", "No process found for given Task Id"),
  PROCESS_REVIEWER_CANNOT_BE_AUTHOR("E124", "Some of the selected Authors have already reviewed this prototype. Reviewers cannot be Authors."),

  /*--Collaborator--*/
  COLLABORATION_INVALID_STATE_ACTION("E120", "Action performed on the collaboration is invalid on current state"),

  /*--SignOff users--*/
  PROCESS_USER_SIGNOFF_ERROR("E125", "User cannot signoff the process as previous users didn't sign off the process."),
  PROCESS_CAN_ONLY_BE_ARCHIVED_BY("E126", "Only account owner, facility admin and author can archive it"),
  PROCESS_EMPTY_STAGE_VALIDATION("E127", "Process must contain at least one stage"),
  PROCESS_EMPTY_TASK_VALIDATION("E128", "Stage must contain at least one task"),


  PROCESS_CANNOT_BE_CREATED_FROM_ALL_FACILITY("E129", "Process cannot be created from All Facility"),
  JOB_CANNOT_BE_CREATED_FROM_ALL_FACILITY("E130", "Job cannot be created from Global Portal"),
  ARCHIVE_REASON_CANNOT_BE_EMPTY("E131", "Archive reason cannot be empty"),
  UNARCHIVE_REASON_CANNOT_BE_EMPTY("E132", "Unarchive reason cannot be empty"),
  PROCESS_RELATION_STATUS_VALIDATION_ERROR("E133", "Process relation status validation error"),
  PROCESS_RELATION_PROPERTY_VALIDATION_ERROR("E134", "Process relation property validation error"),
  PROCESS_RELATION_PROPERTY_VALIDATION_COULD_NOT_RUN_MISSING_DATA("E135", "Could not perform relation property validation due to missing data"),
  PROCESS_RELATION_AUTOMATION_ACTION_ERROR("E136", "Could not perform actions related to the process parameter"),
  CANNOT_ASSIGN_TRAINING_USER_IN_ALL_FACILITY("E137", "Cannot assign training users from Global Portal"),
  PROCESS_CAN_ONLY_BE_UNARCHIVED_BY("E138", "Only Owner, Facility Admin, Author can unArchive it"),
  PROCESS_RECALL_INVALID_STATE("E139", "Process recall invalid state"),
  PROCESS_RECALL_ACCESS_DENIED("E140", "Access denied to recall process"),
  GLOBAL_PROCESS_CAN_ONLY_BE_ARCHIVED_BY("141", "Only account owner and global admin can archive a global process"),
  GLOBAL_PROCESS_CAN_ONLY_BE_UNARCHIVED_BY("142", "Only account owner and global admin can unArchive a global process"),

  PROCESS_PROPERTY_VALUE_SIZE_EXCEEDED("E143", "Process property value size exceeded"),
  AT_LEAST_TWO_REVIEWERS_REQUIRED("E144", "Please select at least two reviewers to proceed. This ensures the process meets the requirement of having at least one reviewer and one approver during signing."),
  APPROVER_REVIEWER_CANNOT_REVISION("145", "As a reviewer/approver, you cannot revise this prototype"),
  PROCESS_ALREADY_ARCHIVED("E145", "Process already archived"),
  APPROVER_REVIEWER_CANNOT_RECALL("146", "As a reviewer/approver, you cannot recall this prototype"),
  PROVIDE_REASON_FOR_RECALL("147", "Provide reason for recalling checklist"),
  CANNOT_ARCHIVE_PROCESS_WITH_ACTIVE_SCHEDULERS("E148", "Process can't be archived as there are active Schedulers for it"),
  // Task
  TASK_INCOMPLETE("E201", "Task Incomplete"),
  TASK_NOT_FOUND("E202", "Task not Found"),
  TIMED_TASK_REASON_CANNOT_BE_EMPTY("E203", "Timed Task reason cannot be empty"),
  PROVIDE_REASON_TO_SKIP_TASK("E204", "Provide reason to skip Task"),
  USER_NOT_ASSIGNED_TO_EXECUTE_TASK("E206", "You are not assigned to this Task"),
  PROVIDE_REASON_TO_FORCE_CLOSE_TASK("E207", "Provide reason to force close Task"),
  OPERATION_CANNOT_BE_PERFORMED_ON_A_COMPLETED_TASK("E208", "Operation cannot be performed on a completed Task"),
  TIMED_TASK_INVALID_OPERATION("E209", "Timed task invalid operation"),
  TASK_NAME_CANNOT_BE_EMPTY("E210", "Task name cannot be empty"),
  TASK_SHOULD_HAVE_ATLEAST_ONE_EXECUTABLE_PARAMETER("E211", "Task should have at least one executable parameter"),
  TASK_NOT_IN_PROGRESS("E212", "Task not in progress"),
  TASK_ALREADY_COMPLETED("E213", "Task already completed"),
  TASK_NOT_ENABLED_FOR_CORRECTION("E214", "Task not enabled for correction"),
  TASK_NOT_SIGNED_OFF("E215", "Task not signed off"),
  TASK_MEDIA_NOT_FOUND("E216", "Task media not found"),
  TIMED_TASK_LT_TIMER_CANNOT_BE_ZERO("E217", "Timer cannot be set to zero"),
  TIMED_TASK_NLT_MIN_PERIOD_CANNOT_BE_ZERO("E218", "Minimum time cannot be zero"),
  TIMED_TASK_NLT_MAX_PERIOD_SHOULD_BE_GT_MIN_PERIOD("E219", "Maximum time should be more than Minimum time"),
  TASK_COMPLETED_ASSIGNMENT_FAILED("E220", "Failed to perform assignment operation on a completed task"),
  FAILED_TO_UNASSIGN_SINCE_USER_PERFORMED_ACTIONS_ON_TASK("E221", "cannot be unassigned since this user is active on this job"),
  FAILED_TO_UNASSIGN_SINCE_USER_SIGNED_OFF_TASK("E222", "cannot be unassigned since this user signed off the task"),
  TASK_ALREADY_ENABLED_FOR_CORRECTION("E223", "Task already enabled for correction"),
  TASK_ENABLED_FOR_CORRECTION("E223", "Error correction has been initiated for tasks but hasn't been completed yet"),
  TASK_ALREADY_IN_PROGRESS("E224", "Task already in progress"),
  TASK_IN_PROGRESS("E224", "Some of the tasks are in progress. Please complete them before completing Job with Exception"),
  TASK_AUTOMATION_INVALID_MAPPED_PARAMETERS("E225", "Task automation refers to parameters that no longer exist or have been archived"),
  TASK_IS_IN_NON_RESUMABLE_STATE("E226", "Task is in non resumable state"),
  TASK_IS_IN_PAUSED_STATE("E227", "Task is in paused state"),
  DEPENDENT_TASK_NOT_ENABLED_FOR_CORRECTION("E214", "Dependent task is not enabled for correction"),
  AUTOMATION_WILL_NOT_RUN_DUE_TO_MISSING_RESOURCES("E215", "Automation not run due to missing resources"),
  CANNOT_UNMAP_PARAMETER("E216", "Cannot unmap parameter as it's in use"),
  PARAMETER_USED_IN_AUTOMATION("E217", "Parameter is linked to automation, Please de-link the parameter from automation"),
  PARAMETER_USED_IN_AUTO_INITIALIZE("E218", "Parameter is linked to auto-initialization, Please de-link the parameter from auto-initialization"),


  PARAMETER_USED_IN_PROPERTY_FILTERS("E219", "Parameter is linked to Resource filters, Please de-link the parameter from Resource filters"),
  PARAMETER_USED_IN_RULES("E220", "Parameter is linked to branching rules, Please de-link the parameter from rules"),
  PARAMETER_USED_IN_DATE_OR_DATETIME_VALIDATIONS("E221", "Parameter used in one or more DATE or DATE TIME Validations. Please de-link the parameter from DATE or DATE TIME Criteria Validation"),
  START_TASK_AUTOMATION_NOT_ALLOWED_FOR_SAME_TASK_PARAMETER("E503", "Start task automation not allowed for same task parameter"),
  TASK_EXECUTION_NOT_IN_COMPLETED_STATE("E228", "Task Execution not in completed state"),
  MASTER_TASK_CANNOT_BE_DELETED("E229", "Master task cannot be deleted"),
  TASK_EXECUTION_ALREADY_IN_PROGRESS_OR_COMPLETED("E230", "Task execution already in progress or completed"),
  TASK_EXECUTION_NOT_FOUND("E231", "Task execution not found"),
  RECURRING_TASK_CANNOT_BE_REPEATED("E232", "Recurring task cannot be repeated"),
  TASK_EXECUTION_CONTAINS_STOP_RECURRENCE("E233", "Task execution contains stop recurrence"),
  TASK_RECURRENCE_NOT_FOUND("E234", "Task recurrence not found"),
  SUBSEQUENT_TASKS_ARE_IN_PROGRESS_OR_COMPLETED("E235", "Subsequent tasks are in progress or completed"),
  PRECEDING_TASKS_ARE_NOT_COMPLETED("E236", "Preceding tasks are not completed"),
  TASKS_ARE_ENABLED_FOR_CORRECTION("E237", "Some of the tasks are enabled for correction. Please confirm/cancel them before starting task"),
  CANNOT_REPEAT_TASK_ALL_PARAMETERS_ARE_HIDDEN_FOR_TASK_EXECUTION("E238", "Cannot repeat task as all parameters are hidden for task execution"),
  PARAMETER_USED_IN_INTERLOCKS("E239", "Parameter is linked to Interlocks, Please de-link the parameter from Interlocks"),
  PARAMETER_USED_IN_CALCULATION("E240", "Parameter used in Calculation. Please de-link the parameter from Calculation"),
  PARAMETER_USED_IN_CREATE_OBJECT_AUTOMATION_MAPPING("E240", "Parameter is linked to create object Automation, Please de-link the parameter"),
  PARAMETER_USED_IN_LEAST_COUNT("E241", "Parameter used in Least Count. Please de-link the parameter from Least Count"),
  SOLO_TASK_LOCKED("E242", "This task is currently in progress and has been locked for solo execution by"),
  TASK_CANNOT_BE_SKIPPED("E224", "Task cannot be skipped as it's already started/completed"),
  PARAMETER_USED_IN_NUMBER_CRITERIA_VALIDATION("E241", "Parameter used in one or more Number Criteria Validations. Please de-link the parameter from Number Criteria Validation"),
  RECURRING_TASK_PREMATURE_START_REASON_MISSING("E243", "Recurring task premature start reason missing"),
  RECURRING_TASK_OVERDUE_COMPLETION_REASON_MISSING("E244", "Recurring task overdue completion reason missing"),
  CHANGE_THE_TASK_DEPENDENCY("E245","This task is prerequisite for another task"),
  FAILED_TO_UNASSIGN_SINCE_USER_GROUP_PERFORMED_ACTIONS_ON_TASK("E221", "cannot be unassigned since this user group is active on this job"),
  FAILED_TO_UNASSIGN_SINCE_USER_GROUP_SIGNED_OFF_TASK("E222", "cannot be unassigned since this user signed off the task"),
  TASK_BULK_VERIFY_SHOULD_HAVE_VERIFICATION("E246", "Bulk Verification is not allowed for tasks with fewer than two parameters requiring self or peer verification" ),

  TASK_CANNOT_BE_COMPLETED_WHEN_PAUSED("E243", "Task cannot be completed when it's in paused state"),

  //Stage
  STAGE_INCOMPLETE("E301", "Stage Incomplete"),
  STAGE_NOT_FOUND("E302", "Stage Not Found"),
  STAGE_NAME_CANNOT_BE_EMPTY("E303", "Stage name cannot be empty"),
  //Parameter
  PARAMETER_INCOMPLETE("E401", "Parameter Incomplete"),
  PARAMETER_NOT_FOUND("E402", "Parameter not found"),
  CANNOT_EXECUTE_PARAMETER_ON_A_COMPLETED_TASK("E403", "Cannot execute parameter on a completed Task"),
  CANNOT_EXECUTE_PARAMETER_ON_A_NONSTARTED_TASK("E404", "Cannot execute parameter on a non started Task"),
  PROVIDE_REASON_FOR_YES_NO_PARAMETER("E405", "Provide reason for yes/no parameter"),
  PROVIDE_REASON_FOR_PARAMETER_PARAMETER_OFF_LIMITS("E406", "Provide reason for parameter off limits"),
  YES_NO_PARAMETER_OPTIONS_NAME_CANNOT_BE_EMPTY("E407", "yes/no parameter option's name cannot be empty"),
  YES_NO_PARAMETER_SHOULD_HAVE_EXACTLY_TWO_OPTIONS("E408", "yes/no parameter should have exactly two options"),
  YES_NO_PARAMETER_TITLE_CANNOT_BE_EMPTY("E409", "yes/no parameter title cannot be empty"),
  MULTISELECT_PARAMETER_OPTIONS_NAME_CANNOT_BE_EMPTY("E410", "Multiselect parameter option's name cannot be empty"),
  MULTISELECT_PARAMETER_OPTIONS_CANNOT_BE_EMPTY("E411", "Multiselect parameter options cannot be empty"),
  SINGLE_SELECT_PARAMETER_OPTIONS_NAME_CANNOT_BE_EMPTY("E412", "Single select parameter option's name cannot be empty"),
  SINGLE_SELECT_PARAMETER_OPTIONS_CANNOT_BE_EMPTY("E413", "Single select parameter options cannot be empty"),
  PROCESS_PARAMETER_OPTIONS_NAME_CANNOT_BE_EMPTY("E414", "Process parameter option's name cannot be empty"),
  PROCESS_PARAMETER_OPTIONS_CANNOT_BE_EMPTY("E415", "Process parameter options cannot be empty"),
  SHOULD_BE_PARAMETER_VALUE_INVALID("E417", "Invalid should-be parameter value(s)"),
  SHOULD_BE_PARAMETER_OPERATOR_CANNOT_BE_EMPTY("E418", "Should-be parameter operator cannot be empty"),
  MATERIAL_PARAMETER_NAME_CANNOT_BE_EMPTY("E419", "Material parameter name cannot be empty"),
  MATERIAL_PARAMETER_LIST_CANNOT_BE_EMPTY("E420", "Material parameter list cannot be empty"),
  MATERIAL_PARAMETER_CANNOT_BE_MANDATORY("E421", "Material parameter cannot be mandatory"),
  INSTRUCTION_PARAMETER_TEXT_CANNOT_BE_EMPTY("E422", "Instruction parameter text cannot be empty"),
  INSTRUCTION_PARAMETER_CANNOT_BE_MANDATORY("E423", "Instruction parameter cannot be mandatory"),
  PARAMETER_EXECUTION_NOT_FOUND("E425", "Parameter execution record not found"),
  PARAMETER_VALUE_NOT_FOUND("E426", "Parameter value record not found"),
  TEMP_PARAMETER_VALUE_NOT_FOUND("E427", "Temporary Parameter value record not found"),
  PARAMETER_EXECUTION_MEDIA_CANNOT_BE_EMPTY("E428", "Media cannot be empty"),
  ONLY_SUPERVISOR_CAN_APPROVE_OR_REJECT_PARAMETER("E429", "Only supervisor can approve or reject parameter"),
  SHOULD_BE_PARAMETER_UOM_CANNOT_BE_EMPTY("E430", "Parameter parameter unit of measurement cannot be empty"),
  SHOULD_BE_PARAMETER_NAME_CANNOT_BE_EMPTY("E431", "Parameter parameter name cannot be empty"),
  SHOULD_BE_PARAMETER_LOWER_VALUE_CANNOT_BE_MORE_THAN_UPPER_VALUE("E432", "Lower value cannot be more than Upper value"),
  CALCULATION_PARAMETER_EXPRESSION_CANNOT_BE_EMPTY("E433", "Calculation parameter expression cannot be empty"),
  CALCULATION_PARAMETER_INVALID_EXPRESSION("E434", "Calculation parameter invalid expression"),
  CALCULATION_PARAMETER_DEPENDENT_PARAMETER_VALUES_NOT_SET("E436", "Some of the parameter values are not set to perform this calculation"),

  CALCULATION_PARAMETER_DEPENDENT_PARAMETERS_NOT_FOUND("E437", "Some of the parameters required to perform this calculation does not exist"),
  CALCULATION_PARAMETER_LABEL_CANNOT_BE_EMPTY("E438", "Calculation parameter label cannot be empty"),
  PARAMETER_LABEL_CANNOT_BE_EMPTY("E439", "Parameter label cannot be empty"),

  NUMBER_PARAMETER_INVALID_VALUE("E440", "Number parameter invalid value"),
  NUMBER_PARAMETER_CUSTOM_VALIDATION_ERROR("E441", "Number parameter custom validation error"),
  NUMBER_PARAMETER_RELATION_PROPERTY_VALIDATION_ERROR("E442", "Number parameter relation property validation error"),
  PARAMETER_RELATION_PROPERTY_VALIDATION_COULD_NOT_RUN_MISSING_DATA("E443", "Could not perform relation property validation due to missing data"),
  PARAMETER_ALREADY_MAPPED("E444", "Parameter has already been mapped"),
  ERROR_UNMAPPING_PARAMETER("E445", "Error unmapping parameters"),
  ERROR_MAPPING_PARAMETER("E446", "Error mapping parameters"),
  ERROR_REORDERING_PARAMETER("E447", "Error reordering parameters"),
  MANDATORY_PARAMETER_VALUES_NOT_PROVIDED("E448", "Mandatory parameter values not provided"),
  UNMAPPED_PARAMETERS_EXISTS("E449", "Process contains parameters that are not mapped"),
  PARAMETER_DATA_INCONSISTENCY("E450", "Parameter Data Inconsistent"),
  PARAMETER_VALIDATIONS_INCONSISTENT_DATA("E451", "Some of the parameters required to perform validations on this parameter does not exist"),
  PARAMETER_AUTO_INITIALIZE_INVALID_DATE("E452", "Parameter is set to auto initialize but data is not found"),

  DATE_PARAMETER_INVALID_VALUE("E453", "Date parameter invalid value"),
  DETECTED_A_CYCLE_IN_CALCULATION_PARAMETER("E454", "Detected a cycle in calculation parameter"),
  CALCULATION_PARAMETER_INVALID_VARIABLE_NAME("E455", "Calculation activity invalid variable name"),
  PARAMETER_CANNOT_BE_ASSIGNED_FOR_CREATE_JOB_FORM("E456", "parameter cannot be assigned for create job form due to verification enabled"),
  USER_NOT_ALLOWED_TO_SELF_VERIFIY_PARAMETER("E458", "User not allowed to self verify parameter"),
  PARAMETER_VERIFICATION_NOT_FOUND("E459", "Parameter verification details not found"),
  PARAMETER_VERIFICATION_INITIATION_FAILED("E460", "Parameter verification initiation failed"),
  SELF_VERIFICATION_NOT_ALLOWED("E461", "Self verification not allowed"),
  PEER_VERIFICATION_NOT_ALLOWED("E462", "Peer verification not allowed"),
  PARAMETER_VERIFICATION_COMPLETION_FAILED("E462", "Parameter verification completion failed"),
  PARAMETER_VERIFICATION_CANCELLATION_FAILED("E463", "Parameter verification cancellation failed"),
  PARAMETER_VERIFICATION_RECALL_FAILED("E464", "parameter verification recall failed"),
  PARAMETER_VERIFICATION_NOT_ALLOWED("E465", "Parameter verification not allowed"),
  CANNOT_EXECUTE_VERIFICATION_PENDING_PARAMETER("E466", "parameter cannot be executed due to pending verification approval"),
  CANNOT_SEND_PARAMETER_FOR_PEER_VERIFICATION("E467", "parameter cannot be sent for peer verification"),

  RESOURCE_PARAMETER_OBJECT_TYPE_CANNOT_BE_EMPTY("E468", "Resource Parameter Object Type cannot be empty"),
  INVALID_FILTER_CONFIGURATIONS("E457", "Invalid filter configurations"),
  VERIFICATION_CANNOT_BE_ENABLED_FOR_CREATE_JOB_FORM_PARAMETER("E469", "verification cannot be enabled for create job form type of parameter"),
  PROCESS_PARAMETER_LINKED_TO_ANOTHER_PROCESS_PARAMETER("E458", "Process parameter is linked to another process parameter, please de-link that process parameter from all other process parameters before deleting it"),
  PARAMETER_EXECUTION_MEDIA_ARCHIVED_REASON_CANNOT_BE_EMPTY("E459", "Reason for archiving media cannot be empty"),
  PARAMETER_EXECUTION_MEDIA_NAME_CANNOT_BE_EMPTY("E460", "Media name cannot be empty"),
  CALCULATION_PARAMETER_VARIABLE_SET_CANNOT_BE_EMPTY("E461", "Calculation parameter variable set cannot be empty"),
  CALCULATION_PARAMETER_PRECISION_CANNOT_BE_NEGATIVE("E474", "Calculation parameter precision cannot be negative"),
  CALCULATION_PARAMETER_PRECISION_CANNOT_BE_MORE_THAN_NINE("E475", "Calculation parameter precision cannot be more than Nine"),
  CJF_PARAMETER_CANNOT_BE_AUTOINITIALIAZED_BY_TASK_PARAMETER("E470", "Process parameter cannot be auto linked by a task parameter"),
  UNCHECKED_PARAMETER_CHOICES_EXITS("E471", "There are unchecked items in parameter, please check all items before verification"),
  CALCULATION_PARAMETER_VARIABLE_CONTAINS_ARCHIVED_PARAMETER("E472", "Calculation parameter variable contains archived parameter"),
  MANDATORY_PARAMETER_PENDING("E473", "Mandatory parameter pending"),
  RESOURCE_PARAMETER_INVALID_SELECTION("E474", "Invalid selection for resource parameter"),
  MULTI_RESOURCE_PARAMETER_INVALID_SELECTION("E475", "Invalid selection for multi resource parameter"),
  ENTERED_VALUE_CANNOT_BE_ACCEPTED_AS_LEASTCOUNT_OF_PARAMETER("E474", "The entered value cannot be accepted as the least count for this parameter is "),
  INVALID_NUMBER_CONFIGURATIONS("E475", "Invalid Number Configurations"),
  LEAST_COUNT_CANNOT_BE_NEGATIVE("E476", "Invalid input. Please enter a value greater than 0"),
  INVALID_SHOULD_BE_CONFIGURATIONS("E477", "Invalid Should be Configurations"),
  LEAST_COUNT_CANNOT_BE_ZERO("E478", "Invalid input. Least Count cannot be zero"),
  SHOULD_BE_PARAMETER_LOWER_VALUE_CANNOT_BE_GREATER_THAN_UPPER_VALUE("E479", "Should be parameter's lower value cannot be greater than upper value"),
  SINGLE_SELECT_RELATION_PROPERTY_VALIDATION_ERROR("E442", "Single select relation property validation error"),
  DATE_RELATION_PROPERTY_VALIDATION_ERROR("E442", "Date relation property validation error"),
  PRECISION_CANNOT_BE_DECIMAL("E479", "Precision has to be integer"),
  SHOULD_BE_PARAMETER_CANNOT_BE_EXECUTED_AS_IT_HAS_BEEN_ALREADY_APPROVED("E480", "Should be parameter value cannot be modified as it has been approved"),
  SHOULD_BE_PARAMETER_CANNOT_BE_EXECUTED_AS_IT_IS_PENDING_FOR_APPROVAL("E481", "Should be parameter value cannot be executed as it is pending for approval"),
  PARAMETER_PENDING_FOR_APPROVAL("E482", "Parameter is pending for approval"),
  SHOULD_BE_PARAMETER_UOM_CASE_INSENSITIVE("E483", "Should be parameter UOM is same"),
  LEAST_COUNT_PARAMETER_ID_MISSING("E484", "Invalid input. Least Count parameter id is missing"),
  LEAST_COUNT_VALUE_NOT_FOUND("E485", "Invalid input. Least Count value not found"),
  LEAST_COUNT_LINKED_PARAMETER_VALUE_NOT_FOUND("E485", "Least Count linked parameter value is missing"),
  LEAST_COUNT_LINKED_PARAMETER_NOT_EXECUTED("E504", "Least Count linked parameter is not executed"),
  LEAST_COUNT_CJF_PARAMETER_CANNOT_BE_LINKED_BY_TASK_PARAMETER("E486", "Process parameter cannot have least count dependency on task parameter"),
  CORRECTION_INITIATOR_REASON("E487", "Correction initiator reason is missing"),
  CORRECTION_CORRECTOR_REVIEWER_USER_LIST("E488", "Correction must have at least one user or user group assigned for both correctors & reviewers"),
  CORRECTION_CORRECTOR_REASON("E489", "Correction corrector remark is missing"),
  CORRECTION_NOT_FOUND("E490", "Correction not found"),

  CORRECTION_CORRECTOR_DID_NOT_MATCH("E491", "Corrector not assigned for correction"),
  CORRECTION_CORRECTOR_VALUE_MISSING("E492", "Mandatory Parameter Corrected value is missing"),
  CORRECTION_REVIEWER_REASON("E493", "Correction reviewer remark is missing"),
  CORRECTION_REVIEWER_DID_NOT_MATCH("E494", "Reviewer not assigned for correction"),
  CORRECTION_AUTO_INITIALIZED_PARAMETER("E495", "Correction cannot be initiated on auto initialized parameter"),
  CORRECTION_CANNOT_DISABLE("E496", "Correction cannot be disabled please complete the initiated corrections first"),
  CORRECTION_ALREADY_EXECUTED("E497", "Correction action could not be performed"),
  CORRECTION_CORRECTOR_REVIEWER_MATCHED("E498", "Corrector cannot be the same as reviewer. Select another reviewer from the dropdown"),
  SELF_VERIFICATION_NOT_COMPLETED("E489", "Self verification not completed"),
  NUMBER_PARAMETER_CRITERIA_VALIDATION_ERROR("490", "Criteria validation linked parameter value missing error"),
  NUMBER_PARAMETER_RESOURCE_VALIDATION_ERROR("491", "Resource validation linked parameter value missing error"),
  CRITERIA_VALIDATION_CJF_PARAMETER_CANNOT_BE_LINKED_BY_TASK_PARAMETER("E491", "Process parameter cannot have criteria validation dependency on task parameter"),
  RESOURCE_VALIDATION_CJF_PARAMETER_CANNOT_BE_LINKED_BY_TASK_PARAMETER("E499", "Process parameter cannot have resource validation dependency on task parameter"),
  DATE_PARAMETER_VALIDATION_CJF_PARAMETER_CANNOT_BE_LINKED_BY_TASK_PARAMETER("E500", "Process parameter cannot have date and date time validation dependency on task parameter"),
  RESOURCE_PROPERTY_VALIDATION_CJF_PARAMETER_CANNOT_BE_LINKED_BY_TASK_PARAMETER("E506", "Process parameter cannot have resource property validation dependency on task parameter"),
  DATE_PARAMETER_VALIDATION_ERROR("E505", "Date and Date Time validation linked parameter value missing error"),
  RESOURCE_PARAMETER_SELECT_ALL_NO_OBJECT_FOUND("E507", "Resource parameter with filter has no object to select"),

  INCORRECT_CONFIGURATION_FOR_SINGLE_SELECT("E409", "Incorrect configuration for single select parameter"),
  //Media
  MEDIA_NOT_FOUND("E501", "Media Not found"),
  MATERIAL_PARAMETER_INVALID_FILE_EXTENSION("E502", "Invalid file uploaded for material parameter"),
  //User
  USER_NOT_FOUND("E601", "User Not found"),
  CANNOT_ARCHIVE_USER("E602", "User cannot be archived since he/she is assigned to active jobs"),
  //Job
  JOB_NOT_FOUND("E701", "Job Not found"),
  JOB_IS_NOT_IN_PROGRESS("E702", "Job is not in progress"),
  JOB_ALREADY_COMPLETED("E703", "Job already completed"),
  JOB_IS_BLOCKED("E704", "Job is in blocked state"),
  JOB_IS_NOT_IN_BLOCKED("E705", "Job is not in blocked state"),
  UNASSIGNED_JOB_CANNOT_BE_STARTED("E706", "Unassigned job cannot be started"),
  JOB_ALREADY_STARTED("E707", "Job already started"),
  UNSUPPORTED_JOB_STATE("E708", "Unsupported job state"),
  ARCHIVED_USER_CANNOT_BE_ASSIGNED_TO_JOB("E709", "Archived User can't be assigned to a Job"),
  JOB_NO_STARTED("E710", "Job not started"),
  USER_ALREADY_ASSIGNED_TO_JOB("E711", "User is already assigned to this Job"),
  JOB_CWE_DETAIL_NOT_FOUND("E712", "Job cwe detail not found for this job"),
  COMMENT_TO_COMPLETE_JOB_WITH_EXCEPTION_CANNOT_BE_EMPTY("E713", "Comment to complete job with exception cannot be empty"),
  JOB_RELATION_MANDATORY("E714", "Relation in this job is mandatory"),
  USER_NOT_ASSIGNED_TO_EXECUTE_JOB("E801", "You are not assigned to this Job"),
  RESOURCE_ALREADY_EXIST("E901", "Resource already Exists"),
  NOT_AUTHORIZED("E1001", "Unauthorized"),
  ACCESS_DENIED("E1002", "Access Denied"),
  RATE_LIMIT_EXCEEDED("E1050", "Too Many Requests, Rate Limit Exceeded. Please try after sometime"),
  FILE_UPLOAD_LIMIT_EXCEEDED("E1101", "File upload size exceeded"),
  FILE_EXTENSION_INVALID("E1102", "File extension invalid"),
  JAAS_SERVICE_ERROR("E1201", "Jaas service error"),
  MANDATORY_PROCESS_PROPERTY_NOT_SET("E1301", "Mandatory process property not set"),
  MANDATORY_JOB_PROPERTY_NOT_SET("E1302", "Mandatory job property not set"),
  JOB_EXPECTED_START_DATE_CANNOT_BE_AFTER_EXPECTED_END_DATE("E1303", "Job expected start date cannot be after expected end date"),
  JOB_EXPECTED_START_DATE_CANNOT_BE_A_PAST_DATE("E1304", "Job expected start date cannot be a past date"),
  JOB_EXPECTED_END_DATE_CANNOT_BE_A_PAST_DATE("E1305", "Job expected end date cannot be a past date"),
  USER_NOT_ALLOWED_TO_CREATE_JOB("E1306", "Current User is not a Trained User. Only trained users are allowed to create this job"),
  JOB_ANNOTATION_NOT_FOUND("E1401", "Job Annotation not Found"),
  CANNOT_EXECUTE_PARAMETER_ON_A_STARTED_JOB("E1307", "Cannot execute parameter on a started Job"),


  //Facility
  FACILITY_NOT_FOUND("E1401", "Facility not Found"),

  // Usecase
  USE_CASE_NOT_FOUND("E1501", "Use Case not Found"),

  // Object Type
  OBJECT_TYPE_NOT_FOUND("E1601", "Object Type not Found"),
  OBJECT_TYPE_MANDATORY_PROPERTIES_NOT_SET("E1602", "Object Type mandatory properties not set"),
  OBJECT_TYPE_PROPERTY_INPUT_TYPE_CANNOT_BE_CHANGED("E1603", "property input type cannot be changed"),
  OBJECT_TYPE_RELATION_TYPE_CANNOT_BE_CHANGED("E1604", "relation type cannot be changed"),
  OBJECT_TYPE_PROPERTY_CANNOT_BE_ARCHIVED("E1605", "object type property cannot be archived"),
  EXTERNAL_ID_CANNOT_BE_CHANGED("E1606", "external Id cannot be changed"),
  RELATION_TARGET_CARDINALITY_CANNOT_BE_CHANGED("E1607", "relation target cardinality cannot be changed"),
  FIXED_PROPERTY_CANNOT_BE_CHANGED("E1608", "object type fixed property cannot be changed"),
  OBJECT_TYPE_MANDATORY_RELATIONS_NOT_SET("E1609", "Object Type mandatory relations not set"),
  ENTITY_OBJECT_NOT_FOUND("E1701", "Entity Object not Found"),
  ENTITY_OBJECT_PROPERTIES_VALIDATION("E1702", "Entity objects properties validation error"),
  ENTITY_OBJECT_PROPERTY_INVALID_INPUT("E1703", "Entity objects property invalid input"),
  ENTITY_OBJECT_DATE_FORMAT_INVALID("E1704", "%s format invalid (expected %s format: %s)"),
  COULD_NOT_CREATE_ENTITY_OBJECT_IN_ALL_FACILITY("E1704", "Entity objects cannot be created from Global Portal"),
  COULD_NOT_UPDATE_ENTITY_OBJECT_IN_ALL_FACILITY("E1705", "Entity objects cannot be updated from Global Portal"),
  COULD_NOT_CREATE_ENTITY_OBJECT_REASON_CANNOT_BE_EMPTY("E1706", "Entity objects cannot be created as reason is empty"),
  COULD_NOT_UPDATE_ENTITY_OBJECT_REASON_CANNOT_BE_EMPTY("E1707", "Entity objects cannot be updated as reason is empty"),
  ENTITY_OBJECT_RELATIONS_MISSING("E1708", "Entity objects relations archived or missing"),
  ENTITY_OBJECT_PROPERTIES_MISSING("E1709", "Entity objects properties archived or missing"),

  RESOURCE_PARAMETER_RELATION_PROPERTY_VALIDATION_ERROR("E1801", "Resource parameter relation property validation error"),
  RESOURCE_PARAMETER_RELATION_PROPERTY_VALIDATION_COULD_NOT_RUN_MISSING_DATA("E1802", "Could not perform relation property validation due to missing data"),
  RESOURCE_PARAMETER_AUTOMATION_ACTION_ERROR("E1803", "Could not perform actions related to resource parameter"),
  OBJECT_ALREADY_ARCHIVED("E1804", "Object is  already archived"),
  OBJECT_ALREADY_UNARCHIVED("E1805", "Object is already unarchived"),
  OBJECT_TYPE_DISPLAY_NAME_ALREADY_EXISTS("E1806", "This name already exists, Please set a unique name for this object type"),
  OBJECT_TYPE_DISPLAY_NAME_INVALID("E1807", "object type display name invalid"),
  OBJECT_TYPE_PROPERTY_DISPLAY_NAME_INVALID("E1810", "property display name invalid"),
  OBJECT_TYPE_PROPERTY_DISPLAY_NAME_ALREADY_EXISTS("E1811", "This name already exists, Please set a unique name for this property"),
  OBJECT_TYPE_RELATION_DISPLAY_NAME_ALREADY_EXISTS("E1812", "This name already exists, Please set a unique name for this relation"),
  OBJECT_TYPE_RELATION_DISPLAY_NAME_INVALID("E1813", "relation display name invalid"),
  OBJECT_TYPE_ARCHIVED_PROPERTY_CANNOT_BE_CHANGED("E1815", "archive property cannot be changed"),
  OBJECT_TYPE_ARCHIVED_RELATION_CANNOT_BE_CHANGED("E1816", "archive property cannot be changed"),
  OBJECT_TYPE_PROPERTY_DROPDOWN_OPTION_DISPLAY_NAME_INVALID("E1817", "option display name invalid"),
  OBJECT_TYPE_PROPERTY_DROPDOWN_OPTION_DISPLAY_NAME_EXISTS("E1818", "option display name already exists"),
  CANNOT_PERFORM_AUTOMATION_ACTION_ON_ARCHIVED_PROPERTY("E1820", "cannot perform automation action on archive property"),
  OBJECT_TYPE_PROPERTY_USED_IN_PROPERTY_FILTERS("E1821", "Object Type Property used in Resource Filters"),
  OBJECT_TYPE_PROPERTY_USED_IN_PROPERTY_VALIDATIONS("E1822", "Object Type Property used in Resource Validations"),
  OBJECT_TYPE_PROPERTY_USED_IN_VALIDATIONS("E1823", "Object Type Property used in Validations"),
  OBJECT_TYPE_PROPERTY_USED_IN_AUTOMATIONS("E1824", "Object Type Property used in Automations"),
  OBJECT_TYPE_PROPERTY_USED_IN_AUTOINITIALIZED_PARAMETERS("E1825", "Object Type Property used in Linked Parameters"),
  OBJECT_TYPE_PROPERTY_USED_IN_INTERLOCK_CONDITIONS("E1826", "Object Type Property used in Conditions"),
  OBJECT_TYPE_RELATION_USED_IN_PROPERTY_FILTERS("E1827", "Object Type Relation used in Resource Filters"),
  OBJECT_TYPE_RELATION_USED_IN_AUTOMATIONS("E1828", "Object Type Relation used in Automations"),
  OBJECT_TYPE_RELATION_USED_IN_AUTOINITIALIZED_PARAMETERS("E1829", "Object Type Relation used in Linked Parameters"),
  OBJECT_TYPE_CREATE_REASON_CANNOT_BE_EMPTY("E1830", "Object type cannot be created as reason cannot be empty"),
  OBJECT_TYPE_UPDATE_REASON_CANNOT_BE_EMPTY("E1830", "Object type cannot be updated as reason cannot be empty"),
  OBJECT_TYPE_PROPERTY_USED_IN_SINGLE_SELECT("E1831", "Object type property cannot be archived as it's used in a single select parameter"),
  OBJECT_EXTERNAL_ID_NOT_UPDATABLE("E1832", "Object External Id property cannot be updated"),
  DATE_DATE_TIME_PARAMETER_RELATION_PROPERTY_VALIDATION_ERROR("E1833", "Date and Date Time parameter relation property validation error"),
  SELECT_PARAMETERS_AUTOINITIALIZED_COULD_NOT_BE_EXECUTED("E1834", "Unable to populate the linked parameter value due to a mismatch in available options"),

  // Automation
  AUTOMATION_NOT_FOUND("E1901", "Automation not Found"),
  CREATE_OBJECT_OR_BULK_CREATE_OBJECT_AUTOMATION_ALREADY_EXISTS("E1902", "Create Object/Bulk Create Object action already exists, multiple create job actions are not allowed"),
  AUTOMATION_CANNOT_BE_PERFORMED_ON_EMPTY_PROPERTY("E1903", "Automation cannot be performed as the Object property value is empty"),

  // CUSTOM VIEW
  CUSTOM_VIEW_NOT_FOUND("E2001", "Custom View Not Found"),
  CUSTOM_VIEW_LABEL_INVALID("E2002", "The custom view name is invalid"),

  //SHORT CODE
  NO_SUCH_SHORT_DATA_FOUND("E3001", "No such short data mapped to given facility id"),
  EMPTY_SHORT_CODE_DATA("E3002", "Empty Short Code data"),
  SHORT_CODE_ALREADY_MAPPED_TO_OBJECT("E3003", "This short code is already mapped to an object"),
  OBJECT_IS_NOT_MAPPED_TO_THIS_FACILITY("E3005", "Object is not mapped to the facility"),
  INVALID_OBJECT_TYPE_SCANNED("E3006", "Object doesn't belong to required object type"),
  UPDATE_SHORT_CODE_REASON("E3007", "QR code update reason cannot be empty"),
  ERROR_CREATING_A_SCHEDULER("E2105", "Error creating a scheduler"),
  //Report

  REPORT_NOT_FOUND("E2001", "Report name not found"),

  // General
  PARAMETER_VERIFICATION_INCOMPLETE("E9002", "parameter verification incomplete"),

  // Sheduler
  SCHEDULER_NOT_FOUND("E2101", "Scheduler not Found"),
  INVALID_SCHEDULER_START_DATE("E2102", "Scheduler Start Date cannot be a past date"),
  INVALID_SCHEDULER_DUE_AFTER_DATE("E2103", "Scheduler invalid Due After date"),
  SCHEDULER_WITH_SAME_NAME_EXIST("E2104", "Scheduler with same name already exist"),
  ERROR_CREATING_A_SCHEDULER_ON_ARCHIVED_PROCESS("E2105", "Error creating a scheduler on archived process"),

  //Branching rules
  RULE_ID_CANNOT_BE_EMPTY("E2201", "Rule Id cannot be empty"),
  RULE_CONSTRAINT_CANNOT_BE_EMPTY("E2202", "Rule Constraint cannot be empty"),
  RULE_INPUT_CANNOT_BE_EMPTY("E2203", "Rule input cannot be empty"),
  RULE_HIDE_OR_SHOW_BOTH_CANNOT_BE_EMPTY("E2204", "Both rule hide or show cannot be empty"),
  INCORRECT_RULE_CONFIGURED("E2205", "Incorrect rule is configured"),
  ALL_PARAMETERS_ARE_HIDDEN_FOR_TASK_EXECUTION("E2206", "All parameters are hidden for task execution"),

  //Variation
  VARIATION_ALREADY_EXISTS("E3001", "Variation already exists"),
  VARIATION_NOT_FOUND("E3001", "Variation not found"),
  VARIATION_NAME_OR_NUMBER_ALREADY_EXISTS("E3002", "Variation name or number not unique"),
  NO_VARIATION_CONFIGURED("E3003", "Variation not configured"),
  CANNOT_DELETE_VARIATION_ON_ONGOING_TASK("E3004", "Cannot delete variation on ongoing task"),


  //Interlocks
  INTERLOCK_NOT_FOUND_FOR_TASK("E2301", "Interlock not found for task"),
  INTERLOCK_INPUT_CANNOT_BE_EMPTY("E2302", "Interlock input cannot be empty"),
  START_TASK_INTERLOCK_NOT_ALLOWED_FOR_SAME_TASK_PARAMETER("E2303", "Start task interlock not allowed for same task parameter"),
  INTERLOCK_CONDITION_CANNOT_BE_VALIDATED_DUE_TO_MISSING_RESOURCES("E2304", "Interlock condition cannot be validated due to missing resources"),
  INTERLOCK_SELECTED_RESOURCE_PROPERTY_VALUE_IS_NOT_UPDATED("E2305", "Could not perform interlock validation due to missing data"),
  CANNOT_PERFORM_INTERLOCK_VALIDATION_ON_ARCHIVED_OBJECT("E2306", "Cannot perform interlock validation on archived object"),
  NUMBER_PARAMETER_INTERLOCK_VALIDATION_ERROR("E2307", "Number parameter interlock validation error"),
  SINGLE_SELECT_INTERLOCK_VALIDATION_ERROR("E2308", "Single select interlock validation error"),
  DATE_INTERLOCK_VALIDATION_ERROR("E2309", "Date interlock validation error"),
  DATE_TIME_INTERLOCK_VALIDATION_ERROR("E2310", "Date time interlock validation error"),

  // TASK DEPENDENCIES
  CYCLIC_TASK_DEPENDENCY("E2401", "Cyclic dependency detected"),
  TASK_DEPENDENCIES_NOT_COMPLETED("E2402", "Task dependencies not completed"),


  // General
  DUPLICATE_RECORD_ERROR("E9001", "A resource with the same unique identifier already exists"),
  REASON_CANNOT_BE_EMPTY("E9003", "Reason cannot be empty"),

  TASK_SCHEDULES_REQUEST_INVALID("E9003", "Task schedules request invalid"),
  INVALID_DATE_DURATION("E9004", "Invalid Date duration"),
  OBJECT_OPTIMISTIC_LOCKING_FAILURE("E9005", "Object Optimistic Lock failure" ),
  INVALID_INPUT("E9006", "Invalid input"),

  // QR parser
  QR_PARSER_NOT_FOUND("E2301", "QR parser not found"),
  QR_PARSER_ALREADY_ARCHIVED("E2302", "QR parser already archived"),
  QR_PARSER_ALREADY_ACTIVE("E2303", "Qr parser already active"),
  INCORRECT_ELEMENT_COPY_TYPE("E2304", "Incorrect element copy type"),

  // User Group
  MANDATORY_FIELDS_MISSING("E2401", "Mandatory fields missing"),
  USER_GROUP_NOT_FOUND("E2402", "User group not found"),
  USER_GROUP_ALREADY_ADDED_TO_CHECKLIST("E2403", "User group already added to process"),
  USER_ALREADY_ADDED_TO_CHECKLIST("E2404", "User already added to checklist"),
  USER_GROUP_ALREADY_EXISTS("E2405", "This group name is already in use"),
  SOME_USERS_ARE_ALREADY_MAPPED_TO_CHECKLIST("E2406", "Some users are already mapped to process"),
  SOME_USER_GROUPS_ARE_ALREADY_MAPPED_TO_CHECKLIST("E2407", "Some user groups are already mapped to process"),
  USER_GROUP_ASSIGNED_TO_IN_PROGRESS_TASKS("E2408", "User group is assigned to in progress tasks"),
  NO_VALID_USER_FOUND_FOR_PEER_VERIFICATION("E2409", "No valid user found for peer verification"),
  INVALID_USER_ROLES("E2410", "Some of the users have invalid roles like System Admin or Global Admin"),
  // Task Executor Lock
  TASK_EXECUTOR_LOCK_ALREADY_EXISTS("E2401", "Task executor lock already exists"),
  INCORRECT_CONFIGURATION_FOR_TASK_EXECUTOR_LOCK("E2402", "Incorrect configuration for task executor lock"),
  TASK_INITIATION_BLOCKED_DUE_TO_TASK_EXECUTOR_LOCK("E2403", "Invalid "),
  // Parameter Exception
  PARAMETER_EXCEPTION_INITIATOR_REASON("E2501", "Exception initiator reason is missing"),
  PARAMETER_EXCEPTION_VALUE("E2502", "Exception deviated value is missing"),
  PARAMETER_EXCEPTION_REVIEWER_REASON("E2503", "Exception reviewer reason is missing"),
  PARAMETER_EXCEPTION_REVIEWER_DID_NOT_MATCH("E2504", "Reviewer not assigned for exception"),
  PARAMETER_EXCEPTION_NOT_FOUND("E2505", "Exception not found"),
  PARAMETER_EXCEPTION_ALREADY_EXECUTED("E2506", "Exception action could not be performed"),
  PARAMETER_EXCEPTION_REASON("E2507", "Exception reason is missing"),
  PARAMETER_EXCEPTION_CHOICE_MISSING("E2508", "Exception deviated choices is missing"),
  VIEW_NAME_IS_ALREADY_IN_USE("E2509", "This view name is already in use"),
  PROPERTY_NOT_FOUND("E2001", "Property not found"),
  PARAMETER_USED_IN_PROPERTY_VALIDATIONS("E2002", "Parameter used in one or more Resource validations. Please de-link the parameter from Resource validations"),
  TASK_CANNOT_BE_STARTED_WHEN_ALL_PARAMETERS_ARE_HIDDEN("E2003", "Task cannot be started as all parameters are hidden" ),
  INCORRECT_EXCEL_COLUMN_FOUND("E2004", "Incorrect excel header format");


  private final String code;
  private final String description;

  ErrorCode(String code, String description) {
    this.code = code;
    this.description = description;
  }

  public String getDescription() {
    return description;
  }

  public String getCode() {
    return code;
  }

  @Override
  public String toString() {
    return code + ": " + description;
  }
}
